apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scafe-azurefile-csi-premium
provisioner: file.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
parameters:
  resourceGroup: training
  storageAccount: scafetrainingsta
  skuName: Premium_LRS
